# Exclusions for SonarCloud Automatic Analysis
sonar.exclusions=**/__tests__/**,**/*.test.ts,**/*.spec.ts,refs/**,**/node_modules/**,**/dist/**,**/prototype/**
sonar.test.inclusions=**/__tests__/**/*.ts,**/*.test.ts,**/*.spec.ts
sonar.cpd.exclusions=**/__tests__/**,**/*.test.ts,**/*.spec.ts

# Issue Exclusions
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=Web:S5725
sonar.issue.ignore.multicriteria.e1.resourceKey=**/dashboard.html
