# Exclusions for SonarCloud Automatic Analysis
sonar.exclusions=refs/**,**/node_modules/**,**/dist/**,**/prototype/**

# Issue Exclusions
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=Web:S5725
sonar.issue.ignore.multicriteria.e1.resourceKey=**/dashboard.html
