sonar.organization=loerei
sonar.projectKey=loerei_HoverSource
sonar.projectName=HoverSource
sonar.sources=packages/babel-plugin-react/src,packages/cli/src,packages/client-injector/src,packages/companion-server/src,packages/overlay-core/src,packages/source-resolver/src
sonar.tests=packages/cli/src/__tests__,packages/companion-server/src/__tests__,packages/overlay-core/src,packages/source-resolver/src/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/build.js
